### ISSUE TITLE
Průměr zůžené části venturiho trubice

### ISSUE THREAD

**Issue by kaklik** [mlab-modules/WINDGAUGE03#1]
Při minulých experimentech byly vytištěny dvě verze nastavení venturiho trubice. 

1. [Starší původní ](https://github.com/mlab-modules/WINDGAUGE03/blob/227db80950e0b65a6c62fdc5e925a1c73ff15f58/cad/configuration.scad#L173)
2. [Nová širší](https://github.com/mlab-modules/WINDGAUGE03/commit/b0895b1da3d8c30087f1f9e28f448d28a0944255#diff-e67ffc8beba17f47e5c5dd346d0a4bdc)

První starší verze byla testována za jízdy na autě, kde nastal stav, že při rychlostech i do 100km/h došlo k saturaci tlakového snímače. Jak ukazuje následující graf. 

![87468694_220922022378877_5567378712086708224_n](https://user-images.githubusercontent.com/1194177/78655957-fbb4a880-78c6-11ea-84bf-6faa56f476c6.png)

Z tohoto důvodu byla vytvořena nová verze, která má větší průměr zúžené části tak, aby se zmenšil tlakový spád.  Tato verze má však průměr zřejmě moc velký a tlakový spád je velmi malý, tím je měření zatíženo velkou chybou. Rozdíl je viditelný na následujícím grafu: 

![90640188_215187579832227_3908752957591519232_n](https://user-images.githubusercontent.com/1194177/78656057-20108500-78c7-11ea-96c5-ac32401cf2fc.png)

Samotný šum pak lépe vynikne, když se měření přenormuje na stejnou škálu: 
![90356613_1113754748961626_7473293449236578304_n](https://user-images.githubusercontent.com/1194177/78656153-47675200-78c7-11ea-92d7-bfd21cdd5e0c.png)

Řešením tohoto problému by zřejmě mělo být upravení průměru zůžení úzké části na nějakou hodnotu mezi oběma aktuálně experimentálně vyzkoušenými průměry a opětovné vyvážení modelu.

**Comment by JanKott** [comment]
Hotovo.
POZOR!
Upravil jsem strukturu repozitáře tak, že v AMF a GCODE složkách už nejsou vygenerované modifikátory, ale je tam komponenta bez modifikátoru a s modifikátory.
Pro tisk použít amf/gcode/WINDGAUGE_R03_mod.gcode který je vyvážený (tedy s modifikátory)!
