### ISSUE TITLE
Tisknutelnost měřící trubice anemometru

### ISSUE THREAD

**Issue by kaklik** [mlab-modules/WINDGAUGE03#10]
Při tisku dochází v horní části výřezu pro ložisko k porouchání perimetrů. 
Tato porucha se projevuje jednak propadnutím perimetrů (i u předchozích variant výtisků). Tyto propadané perimetry lze po vytištění odřezat nožem. 

Nově však vzniká porucha, kdy se díky husté výplni perimetry i nadzvednou, což způsobuje zaražení trysky o model a ztrátu kroků krokového motoru. Následující část je tak tištěna posunutá. 

![image](https://user-images.githubusercontent.com/1194177/88646145-240a2200-d0c5-11ea-8d52-c494ac68fb90.png)

Úplné vyřešení tohoto problému vyžaduje dva kroky. 

1. Snížení hustoty výplně v problematické převislé části otvoru a nebo v celém modifikátoru. 
2. Namodelování podpěr, které by zabránily propadání perimetrů během tisku.  Po tisku se tyto podpěry vylomí.

**Comment by JanKott** [comment]
Zatím jsem vyřešil bod 1 - snížil jsem hustotu výplně v modifikátoru Z z 100% na 90%

**Comment by kaklik** [comment]
Zatím zřejmě dostatečně vyřešeno otočením převislé části trubice směrem k ofuku modelu v tiskárně. Lepší chlazení tiskového modelu tak umožňuje vytištění propadajících se perimetrů.
