### ISSUE TITLE
Optimalizace rozměrů víčka elektroniky anemometru

### ISSUE THREAD

**Issue by kaklik** [mlab-modules/WINDGAUGE03#2]
Aktuální kryt PCB má z předu kruhový průřez 

![image](https://user-images.githubusercontent.com/1194177/82238087-fd967080-9936-11ea-8ad1-a2cf0015df75.png)

Důvodem k tomu, je získání dostatečného prostoru pro montáž PCB.  Tento prostor však zřejmě stále není úplně dostatečný jak ukazují poslední pokusy s tiskem krytu. 

PCB narušuje vrstvy v přední části krytu
![PCB narušuje vrstvy v přední části krytu](https://user-images.githubusercontent.com/1194177/82238610-e015d680-9937-11ea-86e9-06bf0cd62aa5.png)

![97584828_244697976853190_5755182762764009472_n](https://user-images.githubusercontent.com/1194177/82238883-400c7d00-9938-11ea-98f9-e3475e419283.png)

U šroubů není možné vytisknout dostatečně kvalitní stěnu a most: 
![image](https://user-images.githubusercontent.com/1194177/82238729-09366700-9938-11ea-98fa-b513ea9b1ab0.png)

![97137646_1648315295334842_636777421877542912_n](https://user-images.githubusercontent.com/1194177/82238899-44389a80-9938-11ea-90f1-6f9682327145.png)

Jedním z řešení tohoto problému může být deformace kapkového krytu pomocí transformace [scale, nebo resize](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Transformations#scale).

Použití takové transformace by umožnilo získat větší šířku kapky v ose X bez zvětšování její výšky. 

Pro případ získání prostoru pro šrouby je možné šrouby natočit v krytu od PCB tak aby byl u hlaviček šroubů získán větší prostor na materiál krytu. Šrouby pak nebudou rovnoběžné ale sbíhavé.

**Comment by JanKott** [comment]
Vyřešeno v rámci issue https://github.com/MLAB-project/Modules/issues/12 zmenšením prostoru pro kabely v commitu https://github.com/mlab-modules/WINDGAUGE03/commit/eab44c50f7cb2b2a021b74fd0d824a2697d4029c

Transformace již použitá byla, ale nepodařilo se mi s jejím použitím v rozumné míře zachovat stávající prostor pro kabely.
