### ISSUE TITLE
Zub na kanálku kabelů vadí při protahování vodičů.

### ISSUE THREAD

**Issue by kaklik** [mlab-modules/WINDGAUGE03#3]
Těsně pod konektorem na PCB se senzory je na přívodním kanálků vodičů zub při vyústění ke konektoru.  

![image](https://user-images.githubusercontent.com/1194177/83415764-ed46c100-a41f-11ea-8db8-b7210d2ce6bc.png)

Vzhledem k tomu, že se vodiče protahují směrem od otočného ložiska k PCB, tak tento zub velmi výrazně komplikuje protožení kabeláže.  Při montáži jsem jej ručně zahladil pájkou, abych vůbec byl schopen kanálkem protáhnout vodiče. 

Ani druhá stěna kanálku na tom není úplně nejlépe: 
![image](https://user-images.githubusercontent.com/1194177/83416116-79f17f00-a420-11ea-9d45-4c07ea87d4cb.png)

Očekávaným řešením takového  kanálku je plynulé vyústění až na povrch modelu bez zubu o který by se vodiče mohly při protahování zaseknout. 

V aktuálním řešení by to možná mohlo jít namodelovat tím způsobem, že kanálek vodičů bude protažen až naprovrch skrz již existující  "trychtýř", tím pravděpodobně vznikne nevzhledná kombinace trychtýře a kanálku, která ale umožní protožení vodičů. 

V případě že by se našlo nějaké estetičtější řešení, tak by to určitě bylo přínosné.

**Comment by JanKott** [comment]
Zuby odstraněny. K otestování.

**Comment by kaklik** [comment]
Testem ověřeno, že zub je odstraněn.
