### ISSUE TITLE
Tuhost uchycení na otočném ložisku

### ISSUE THREAD

**Issue by kaklik** [mlab-modules/WINDGAUGE03#4]
V důsledku zvětšení průměru kanálku pro vodiče (který teď umožňuje protáhnout vodiče i s kontakty), došlo k odstranění dosedací plochy trnul ložiska.  
Nově je tak snadné otočný díl narazit na trn ložiska tak, že drhne. Navíc odstranil i část boční stěny, takže otočný díl se na ložisku dovede viklat.

![image](https://user-images.githubusercontent.com/1194177/83420477-fd15d380-a426-11ea-82db-ed13a235ae9c.png)

Řešením současného stavu zřejmě je trochu precizněji vyřešit napojení kanálku vodičů na otvor pro trn ložiska.  Otvor pro trn ložiska tak musí končit osazením, které bude omezovat zasunutí ložiska tak, aby byl umožněn prostup vodičů, ale zároveň nesmí být ložisko zasunutu tak hluboko, aby mohlo drhnout. 
Představa o tvarovém provední spoje je nakreslena v řezu na následujícím obrázku: 

![image](https://user-images.githubusercontent.com/1194177/83431524-c09ea380-a437-11ea-9de2-4bc611b6a90d.png)

Na horní hranu ložiska tak dosedá tištěný díl, který ložisko obepíná i z boku.  Vodiče pak prostupují užším otvorem do kanálku pro vodiče. 
Kanálek je ve směru k ložisku zkosený, aby bylo možné bez potíží vytáhnout vodiče zpět i s konektory.  (toto řešení je velmi podobné aktuálnímu provedení tlakových kanálků ke snímači)

Rozměry ložiska lze vyčíst z následujících měření:

![image](https://user-images.githubusercontent.com/1194177/83428294-694a0480-a432-11ea-93cc-bc00c4753dc0.png)

![image](https://user-images.githubusercontent.com/1194177/83428491-c5ad2400-a432-11ea-999f-61c9b5522401.png)

**Comment by JanKott** [comment]
K otestování

**Comment by kaklik** [comment]
Zlepšení geometrie vstupního otvoru zlepšilo tuhost uložení na ložisku.
