### ISSUE TITLE
Uložení servisní délky vodičů

### ISSUE THREAD

**Issue by kaklik** [mlab-modules/WINDGAUGE03#6]
Aktuálně navržené řešení uložení vodičů omotáním okolo PCB je prakticky nerealizovatelné.  Problémem je, že nelze udržet vodiče správně umístěné pod víčkem při nasazování víčka. 

Nově navržený kanálek pro přivedení vodičů je však dostatečně tlustý na to, aby jím bylo možné protáhnout vodiče i s nakrimpovanými kontakty konektoru. Tím je umožněno zcela nové řešení, že by vodiče byly rovnou správně dlouhé a mohly být přivedeny rovnou do konektoru. 
Délka vodičů ale nikdy přesně správná nebude, pouze přibližně. Takže zde je potřeba mít nějakou co největší rezervu. Aktuálně jsem však vyzkoušel, že kanálek je tak široký že v něm vzniká asi 15mm rezerva délky, kterou do něj lze natlačit.  (Možná by bylo možné tuto rezervu zvětšit)

Případně by bylo možná udělat místo pro vodiče vytvořením druhého kanálku z protější strany, než kde vede teď. (Tento kanálek by asi mohl být slepý a přebytečná délka vodiče se do něj natlačí od PCB z vrchní strany)

Vyplývá z toho ale že je zřejmě potřeba obnovit původní menší kapkovitý kryt bez kulatých rohů. Ten byl lepší neboť nespotřebovával tolik materiálu a neměl takový aerodynamický odpor.

**Comment by JanKott** [comment]
Zrušil jsem uložení vodiče pod víčko a přidal jsem více místa u vstupu do kanálku pro kabely.
Prosím otestovat, zda je to takto vyhovující.

**Comment by kaklik** [comment]
Vodiče lze ukládat do nového tlustého kanálku, který vodiči přivádí. 

![image](https://user-images.githubusercontent.com/1194177/84377322-b6706800-abe2-11ea-8782-2e324688b909.png)
