### ISSUE TITLE
Výška těžiště nad otočným ložiskem

### ISSUE THREAD

**Issue by kaklik** [mlab-modules/WINDGAUGE03#8]
Aby otočný díl dobře držel na ložisku anemometru, tak je výhodné, aby měl co nejníže těžiště a nedocházelo tak k vyvracení ložiska. 

Toho lze dosáhnout posunutím  hmotnosti, která vyvažuje anemometr co nejvíce dolů.

**Comment by JanKott** [comment]
Vrátil jsem Z modifikátor a težiště položil co nejníže.
