### ISSUE TITLE
Zajištění anemometru na otočném ložisku

### ISSUE THREAD

**Issue by kaklik** [mlab-modules/WINDGAUGE03#9]
Při vyšších rychlostech proudění okolo anemometru došlo k vyckvaknutí otočného dílu z trnu ložiska. 
Záležitost je potřeba řešit, protože to jednak způsobilo, že do ložiska začala téct voda a zároveň se může stát, že stejným způsobem anemometr vypadne i při nižší rychlosti. 

Řešením by mohlo být stažení trnu symetrickými šrouby, tak aby otočný díl byl na trnu mírně zdeformován.  Je ale důležité, aby vnější povrch krytu ze strany šroubů nebyl nijak spojen s vnitřním (suchým) objemem pro ložisko. 

Jedna z možných realizací tohoto řešení by mohla vypadat následovně: 

![image](https://user-images.githubusercontent.com/1194177/84661107-213edd80-af1a-11ea-9a4f-d85a99b11be6.png)

Šrouby by tak byly symetricky po obou stranách otvoru pro ložisko, tak aby co nejtěsněji svíraly vytištěné pozdro pro ložisko. Cílem je zajistit, že po utažení šroubů se pouzdro mírně zdeformuje do oválu.  Deformace ostatních částí anemometru by tak pokud možno měla zůstat minimální. 

Issue je pokračováním původního https://github.com/MLAB-project/Modules/issues/17

**Comment by JanKott** [comment]
Otvory pro šrouby jsem tedy, dle domluvy, udělal horizontálně.

**Comment by JanKott** [comment]
Uzavřeno omylem - k otestování.

**Comment by kaklik** [comment]
Anemometr teď drží na ložisku srovnatelně s celkovou tuhostí ložiska.
